### ISSUE TITLE
Error with number of results

### ISSUE THREAD

**Issue by Chocapikk** [zoomeye-hk/ZoomEye-python#1]
Trying a query with 1000 results

![Screenshot from 2024-03-26 17-22-36](https://github.com/zoomeye-hk/ZoomEye-python/assets/88535377/ba29a03e-57b7-4bd8-8783-4a38c0fcae38)

Have only 500 results

![Screenshot from 2024-03-26 17-14-33](https://github.com/zoomeye-hk/ZoomEye-python/assets/88535377/c7e8d404-8e67-4b8b-a5f1-8770bdefc6a8)

**Comment by performonkey** [comment]
The number of returned data items will be limited according to the plan of your account. `Membership` and `Professional` are limited to a maximum of 500 items returned. Thank you for your feedback, we will optimize the package limit tips in the future.
